import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { compileCatalog } from './locale-catalog.mjs';
const root = path.resolve(import.meta.dirname, '..');
const read = file => fs.readFileSync(path.join(root,file),'utf8');
const check = process.argv.includes('--check');
const sources = ['localization/common.json', ...['catalog','template','dealer'].map(kind=>`localization/${kind}.reviewed.json`)];
const common = JSON.parse(read(sources[0]));
const rows = sources.slice(1).flatMap(file=>JSON.parse(read(file)));
const { en, bg, sourceKeys, ambiguousAliases } = compileCatalog(common,rows);
const dealerRows = JSON.parse(read('localization/dealer.reviewed.json'));
const dealerSourceKeys = Object.fromEntries(dealerRows.map(row=>[row.source,row.key]));
const content = '// Generated by scripts/build-locales.mjs; edit localization catalogs.\n' + Object.entries({en,bg,sourceKeys,dealerSourceKeys,ambiguousAliases}).map(([name,value])=>`export const ${name} = ${JSON.stringify(value,null,2)} as const;\n`).join('');
const hash = data => createHash('sha256').update(data).digest('hex');
const manifest = JSON.stringify({schemaVersion:2,enabledLocales:['en','bg'],messages:Object.keys(en).length,catalogSha256:hash(content),sources,sourceSha256:Object.fromEntries(sources.map(file=>[file,hash(read(file))])),policySha256:hash(read('src/lib/locale/policy.ts')),ambiguousAliases,activeAmbiguousAliases:0,aliasPolicy:'Ambiguous aliases are excluded. Render their context-specific message keys.'},null,2)+'\n';
for (const [file,data] of [['src/lib/locale/catalog.ts',content],['localization/generated-manifest.json',manifest]]) {
  if (check) { if (read(file)!==data) throw Error('Generated locale drift: '+file); }
  else fs.writeFileSync(path.join(root,file),data);
}
console.log(JSON.stringify({status:check?'checked':'generated',messages:Object.keys(en).length,aliases:Object.keys(sourceKeys).length,quarantinedAliases:ambiguousAliases.length,activeAmbiguousAliases:0}));
