import assert from 'node:assert/strict';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { launchBrowser, previewUrl } from './browser.mjs';

const base = previewUrl();
const output = 'artifacts/enquiry-smoke';
await mkdir(output, { recursive: true });
const browser = await launchBrowser();
const photo = await readFile('static/assets/images/lead/day-night-stock-01.webp');
const results = [];
try {
  for (const width of [320, 390, 844, 1440]) {
    const page = await browser.newPage({ viewport: { width, height: width === 844 ? 390 : 900 } });
    const errors = [];
    const posts = [];
    page.on('pageerror', (error) => errors.push(error.message));
    page.on('request', (request) => { if (request.method() === 'POST' && request.frame() === page.mainFrame()) posts.push(request.url()); });
    await page.addInitScript(() => {
      Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (text) => { window.__copied = text; } } });
      Object.defineProperty(navigator, 'share', { configurable: true, value: async (data) => { window.__shared = { text: data.text, files: data.files?.length || 0 }; } });
      Object.defineProperty(navigator, 'canShare', { configurable: true, value: () => true });
    });
    await page.goto(`${base}/contact?topic=trade-in`, { waitUntil: 'networkidle' });
    const start = page.getByRole('button', { name: 'Предложи автомобил', exact: true });
    await start.click();
    const dialog = page.locator('.dn-enquiry');
    assert.equal(await dialog.getAttribute('open'), '');
    assert.equal(await page.evaluate(() => getComputedStyle(document.body).position), 'fixed');
    await page.getByRole('button', { name: 'Продължи', exact: true }).click();
    assert.equal(await dialog.locator('input[name="make"]').evaluate((input) => input === document.activeElement), true, 'Required make must block progression');
    await dialog.locator('input[name="make"]').fill('Audi');
    await dialog.locator('input[name="model"]').fill('A6 Avant');
    await dialog.locator('input[name="year"]').fill('2020');
    await dialog.locator('input[name="mileage"]').fill('85000');
    await dialog.locator('input[name="budget"]').fill('35000');
    await page.screenshot({ path: `${output}/sell-details-${width}.png` });
    await page.getByRole('button', { name: 'Продължи', exact: true }).click();
    const files = dialog.locator('input[type="file"]');
    await files.setInputFiles({ name: 'bad.txt', mimeType: 'text/plain', buffer: Buffer.from('not a photo') });
    assert.match(await dialog.locator('[role="alert"]').innerText(), /JPG/);
    await files.setInputFiles({ name: 'large.jpg', mimeType: 'image/jpeg', buffer: Buffer.alloc(10 * 1024 * 1024 + 1) });
    assert.match(await dialog.locator('[role="alert"]').innerText(), /10 MB/);
    await files.setInputFiles(Array.from({ length: 7 }, (_, index) => ({ name: `car-${index}.webp`, mimeType: 'image/webp', buffer: photo })));
    assert.equal(await dialog.locator('.dn-enquiry-photo-grid img').count(), 6);
    await dialog.locator('.dn-enquiry-photo-grid img').first().evaluate((img) => img.decode());
    await dialog.getByRole('button', { name: 'Премахни car-0.webp', exact: true }).click();
    assert.equal(await dialog.locator('.dn-enquiry-photo-grid img').count(), 5);
    await dialog.locator('textarea').fill('Редовно обслужван.');
    await dialog.locator('input[autocomplete="name"]').fill('Тест');
    await dialog.locator('input[type="tel"]').fill('+359 (88) 123-45-67');
    await page.screenshot({ path: `${output}/sell-photos-${width}.png` });
    await page.getByRole('button', { name: 'Прегледай запитването', exact: true }).click();
    assert.match(await dialog.locator('pre').innerText(), /Audi A6 Avant/);
    assert.match(await dialog.locator('pre').innerText(), /85000/);
    await page.getByRole('button', { name: 'Копирай текста', exact: true }).click();
    assert.match(await page.evaluate(() => window.__copied), /Audi A6 Avant/);
    await page.getByRole('button', { name: 'Сподели запитването', exact: true }).click();
    assert.equal(await page.evaluate(() => window.__shared.files), 5);
    await page.screenshot({ path: `${output}/sell-review-${width}.png` });
    await page.keyboard.press('Escape');
    assert.equal(await start.evaluate((button) => document.activeElement === button), true);
    assert.notEqual(await page.evaluate(() => getComputedStyle(document.body).position), 'fixed');
    await start.click();
    assert.match(await dialog.locator('pre').innerText(), /Audi A6 Avant/, 'Closing must retain the draft');
    assert.equal(await dialog.locator('.dn-enquiry-review-photos img').count(), 5);
    await page.keyboard.press('Escape');

    await page.goto(`${base}/contact?topic=import`, { waitUntil: 'networkidle' });
    const link = page.locator('#enquiry-listing-link');
    for (const value of ['', 'javascript:alert(1)', 'https://user:pass@example.com']) {
      await link.fill(value);
      await page.getByRole('button', { name: 'Продължи с обявата', exact: true }).click();
      assert.equal(await page.locator('#enquiry-link-error').isVisible(), true);
      assert.equal(await dialog.isVisible(), false);
    }
    await link.fill('https://example.com/car?id=12#photos');
    await page.getByRole('button', { name: 'Продължи с обявата', exact: true }).click();
    assert.match(await dialog.locator('.dn-enquiry-selected-link').innerText(), /id=12#photos/);
    await page.getByRole('button', { name: 'Продължи', exact: true }).click();
    assert.equal(await files.count(), 0, 'Import must not expose selling photos');
    await dialog.locator('textarea').fill('Автоматик, до 40 000 евро.');
    await page.getByRole('button', { name: 'Прегледай запитването', exact: true }).click();
    assert.match(await dialog.locator('pre').innerText(), /id=12#photos/);
    await page.screenshot({ path: `${output}/import-review-${width}.png` });
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: /Нямам обява/ }).click();
    assert.equal(await dialog.locator('input[name="make"]').isVisible(), true, 'Changing from link to no-link must revalidate vehicle fields');
    await page.getByRole('button', { name: 'Продължи', exact: true }).click();
    assert.equal(await dialog.locator('input[name="make"]').evaluate((input) => input === document.activeElement), true);
    await page.keyboard.press('Escape');
    await link.fill('https://example.com/another-car');
    await page.getByRole('button', { name: 'Продължи с обявата', exact: true }).click();
    assert.match(await dialog.locator('.dn-enquiry-selected-link').innerText(), /another-car/);
    await page.keyboard.press('Escape');
    await page.reload({ waitUntil: 'networkidle' });
    await page.getByRole('button', { name: /Нямам обява/ }).click();
    await dialog.locator('input[name="make"]').fill('BMW');
    await dialog.locator('input[name="model"]').fill('X3');
    await page.getByRole('button', { name: 'Продължи', exact: true }).click();
    await page.getByRole('button', { name: 'Прегледай запитването', exact: true }).click();
    assert.match(await dialog.locator('pre').innerText(), /BMW X3/);
    const geometry = await dialog.evaluate((element) => ({ overflow: element.scrollWidth - element.clientWidth, height: element.getBoundingClientRect().height, viewport: window.innerHeight }));
    assert.ok(geometry.overflow <= 1 && geometry.height <= geometry.viewport);
    await page.keyboard.press('Tab');
    assert.equal(await dialog.evaluate((element) => element.contains(document.activeElement)), true);
    assert.deepEqual(errors, []);
    assert.deepEqual(posts, [], 'Drafts must not be sent to a server');
    results.push({ width, passed: true, geometry, pageErrors: errors.length, serverSubmissions: posts.length });
    await writeFile(`${output}/report.json`, JSON.stringify({ generatedAt: new Date().toISOString(), base, results }, null, 2));
    console.log(`PASS sell/import forms, photos, review, share, draft, focus at ${width}px`);
    await page.close();
  }
  await writeFile(`${output}/report.json`, JSON.stringify({ generatedAt: new Date().toISOString(), base, results }, null, 2));
} catch (error) {
  results.push({ passed: false, error: error.stack });
  throw error;
} finally { await browser.close(); await writeFile(`${output}/report.json`, JSON.stringify({ generatedAt: new Date().toISOString(), base, results }, null, 2)); }
