p = 'src/lib/data/journeys.ts'
s = (root/p).read_text(encoding='utf8').replace("import { featuredVehicles }", "import type { FinanceSelection } from './finance';\nimport { featuredVehicles }")
s = s.replace("topic: 'inspection' | 'leasing' = 'inspection')", "topic: 'inspection' | 'leasing' = 'inspection', finance?: FinanceSelection)")
s = s.replace("  return `/contact?${new URLSearchParams({ topic, vehicle: String(id) })}`;", "  const params = new URLSearchParams({ topic, vehicle: String(id) });\n  if (topic === 'leasing' && finance) {\n    params.set('down_payment', String(finance.downPaymentEur));\n    params.set('term', String(finance.termMonths));\n  }\n  return `/contact?${params}`;")
put(p, s)
p = 'src/lib/components/vehicles/VehicleFinanceCalculator.svelte'
s = (root/p).read_text(encoding='utf8').replace("  import { vehicleContactHref }", "  import { financePolicy, normalizedDownPayment as clampDownPayment } from '$data/finance';\n  import { vehicleContactHref }")
s = s.replace('const financeTerms = [12, 24, 36, 48, 60] as const;', 'const financeTerms = financePolicy.terms;').replace('>(60);', '>(financeTerms[financeTerms.length - 1]);')
s = s.replace('Math.min(Math.max(Number(downPaymentEur) || 0, 0), priceEur)', 'clampDownPayment(downPaymentEur, priceEur)').replace('step="500"', 'step={financePolicy.downPaymentStepEur}')
s = s.replace("vehicleContactHref(vehicleId, 'leasing')", "vehicleContactHref(vehicleId, 'leasing', { downPaymentEur: normalizedDownPayment, termMonths })")
s = s.replace('<h2>Калкулатор за финансиране</h2>', '<h3>Планирайте бюджета</h3>').replace('header h2', 'header h3').replace('font-size: 24px;', 'font-size: var(--dn-text-card);').replace('min-height: 50px;', 'min-height: var(--dn-control-height);').replace('font-size: 17px;', 'font-size: var(--dn-text-body);')
put(p, s)
put('src/routes/contact/+page.ts', "import { selectedVehicle } from '$data/journeys';\nimport { resolveContactTopic, resolveImportUrl } from '$data/company';\nimport { parseFinanceSelection } from '$data/finance';\nimport type { PageLoad } from './$types';\n\nexport const load: PageLoad = ({ url }) => {\n  const topic = resolveContactTopic(url.searchParams.get('topic'));\n  const vehicle = ['inspection', 'leasing'].includes(topic.id) ? selectedVehicle(url.searchParams.get('vehicle')) : null;\n  return {\n    topic, vehicle,\n    finance: topic.id === 'leasing' && vehicle ? parseFinanceSelection(url.searchParams, vehicle.priceEur) : null,\n    importUrl: topic.id === 'import' ? resolveImportUrl(url.searchParams.get('vehicle_url')) : null\n  };\n};\n")
p = 'src/routes/contact/+page.svelte'
s = (root/p).read_text(encoding='utf8').replace('<ContactIntent vehicle={data.vehicle}', '<ContactIntent finance={data.finance} vehicle={data.vehicle}'); put(p, s)
p = 'src/lib/components/company/ContactIntent.svelte'
s = (root/p).read_text(encoding='utf8').replace("  import type { Vehicle }", "  import type { FinanceSelection } from '$data/finance';\n  import { formatVehiclePrice } from '$data/inventory';\n  import type { Vehicle }")
s = s.replace('topic, vehicle = null, importUrl = null', 'topic, vehicle = null, importUrl = null, finance = null').replace('importUrl?: string | null }', 'importUrl?: string | null; finance?: FinanceSelection | null }')
s = s.replace("    {#if topic.id === 'import' && importUrl}", '    {#if finance}\n      <dl class="dn-contact-finance" aria-label="Избран ориентир за финансиране">\n        <div><dt>Първоначална вноска</dt><dd>{formatVehiclePrice(finance.downPaymentEur)}</dd></div>\n        <div><dt>Срок</dt><dd>{finance.termMonths} месеца</dd></div>\n      </dl>\n    {/if}\n\n    {#if topic.id === \'import\' && importUrl}')
s = s.replace('<style>', '<style>\n  .dn-contact-finance { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; margin: 20px 0 0; }\n  .dn-contact-finance > div { padding: 12px; border-radius: var(--dn-radius-control); background: var(--dn-mobile-canvas); }\n  .dn-contact-finance dt { color: var(--dn-muted); font-size: var(--dn-text-meta); }\n  .dn-contact-finance dd { margin: 6px 0 0; color: var(--dn-ink); font-size: var(--dn-text-lead); font-weight: 650; }')
put(p, s)
p = 'src/routes/listing-detail-v1/[id]/+page.svelte'
s = (root/p).read_text(encoding='utf8').replace('VehicleFinanceCalculator', 'VehicleFinancing')
s = s.replace("  import { bodyLabel }", "  import { imageMedia } from '$data/image-media';\n  import { bodyLabel }").replace('  const phoneLinkAttributes', '  const vehicleImage = $derived(imageMedia(data.vehicle.image));\n  const phoneLinkAttributes')
s = s.replace('src={data.vehicle.image}', 'src={vehicleImage.src} srcset={vehicleImage.srcset} sizes="(max-width: 991px) 100vw, 65vw"')
s = re.sub(r'            <section class="dn-detail-card dn-detail-dealer".*?</section>\n', '', s, flags=re.S)
s = s.replace('<h2 id="location-title">Локация</h2>', '<h2 id="location-title">{brand.name}</h2>\n                <a class="dn-detail-location-phone" {...phoneLinkAttributes}>{brand.phone}</a>')
s = s.replace('<p class="dn-detail-summary__availability">', '<p class="dn-detail-summary__facts">{data.vehicle.year} · {data.vehicle.mileage} · {data.vehicle.transmission}</p>\n              <p class="dn-detail-summary__availability">')
s = s.replace('{#each data.recommendations as vehicle (vehicle.id)}', '{#each data.recommendations as vehicle (vehicle.id)}\n              {@const image = imageMedia(vehicle.image)}')
s = s.replace("resolve(vehicle.href as '/listing-detail-v1/1')", "resolve('/listing-detail-v1/[id]', { id: String(vehicle.id) })").replace('src={vehicle.image} alt="" width="420"', 'src={image.src} srcset={image.srcset} sizes="(max-width: 640px) 122px, 33vw" loading="lazy" alt="" width="420"')
put(p, s)
p = 'src/routes/listing-detail-v1/[id]/detail.css'
s = (root/p).read_text(encoding='utf8').replace('  .dn-detail-dealer { grid-row: 6; }\n', '').replace('#location { grid-row: 7; }', '#location { grid-row: 6; }')
s = s.replace('@media (max-width: 1199px) {', '.dn-detail-finance-card { padding: 0; border: 0; overflow: hidden; }\n.dn-detail-summary__facts { margin: 10px 0 0; color: var(--dn-muted); font-size: var(--dn-text-meta); line-height: 1.5; }\n.dn-detail-location-phone { display: inline-flex; min-height: var(--dn-control-height); align-items: center; font-weight: 650; color: var(--dn-ink); }\n.dn-detail-location-card__header { flex-wrap: wrap; }\n\n@media (max-width: 1199px) {', 1)
s = s.replace('  .dn-detail-sidebar { position: static; }', '  .dn-detail-sidebar { position: static; }\n  .dn-detail-summary__actions { display: none; }\n  .dn-detail-finance-card { padding: 0; }')
s = s.replace('  .dn-detail-dealer,\n', '').replace('  .dn-detail-dealer__header img { width: 144px; height: 46px; }\n', '')
s = s.replace('  .dn-detail-location-card h2 { font-size: 22px; }', '  .dn-detail-location-card h2 { font-size: 22px; }\n  .dn-detail-finance-card { padding: 0; }')
put(p, s)
p = 'src/lib/styles/tokens.css'; s = (root/p).read_text(encoding='utf8').replace(':root {', ':root {\n  --dn-control-height: 44px;\n  --dn-page-gutter: 12px;\n  --dn-section-gap: 32px;').replace('--dn-mobile-detail-bar-height: 67px', '--dn-mobile-detail-bar-height: 60px'); put(p, s)
p = 'src/lib/components/layout/Header.svelte'; s = (root/p).read_text(encoding='utf8').replace('min-height: 50px;', 'min-height: var(--dn-control-height);'); put(p, s)
