"""Deterministic responsive exports. Requires Pillow; not needed to run/build the app."""
from pathlib import Path
from PIL import Image
import hashlib, json

root = Path(__file__).resolve().parents[1]
static = root / 'static'
target = static / 'assets/images/responsive'
target.mkdir(parents=True, exist_ok=True)
patterns = ['assets/images/template/*.png', 'assets/images/lead/day-night-stock-*.webp', 'assets/images/blog/*.jpg', 'assets/images/lead/day-night-collection-banner-v2.webp']
inputs = sorted({p for pattern in patterns for p in static.glob(pattern)})
manifest, evidence = {}, []
for source in inputs:
    raw = source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    with Image.open(source) as image:
        image.load()
        widths = [w for w in (320, 640, 960) if w <= image.width]
        if not widths: continue
        exports = []
        for width in widths:
            filename = f'{source.stem}-{digest[:8]}-{width}.webp'
            destination = target / filename
            height = round(width * image.height / image.width)
            image.resize((width, height), Image.Resampling.LANCZOS).save(destination, 'WEBP', quality=86, method=6)
            with Image.open(destination) as check: check.verify()
            exports.append({'src': '/' + destination.relative_to(static).as_posix(), 'width': width, 'bytes': destination.stat().st_size})
        original_path = '/' + source.relative_to(static).as_posix()
        default = next((item for item in exports if item['width'] == 640), exports[-1])
        manifest[original_path] = {'src': default['src'], 'srcset': ', '.join(f"{item['src']} {item['width']}w" for item in exports), 'width': image.width, 'height': image.height}
        evidence.append({'source': original_path, 'sha256': digest, 'originalBytes': len(raw), 'exports': exports})
module = '// Generated by scripts/export-images.py. Original art is preserved; no new stock photography.\n'
module += 'type ImageMedia = { src: string; srcset?: string; width?: number; height?: number };\n'
module += 'const responsiveImages: Readonly<Record<string, ImageMedia>> = ' + json.dumps(manifest, indent=2) + ';\n\n'
module += "export function imageMedia(src: string): ImageMedia {\n  return responsiveImages[src.split('?')[0]] ?? { src };\n}\n"
(root / 'src/lib/data/image-media.ts').write_text(module, encoding='utf8')
(root / 'provenance/responsive-images-2026-09-12.json').write_text(json.dumps(evidence, indent=2), encoding='utf8')
print(f'Exported {len(manifest)} source images. Originals retained, dimensions verified.')
